{{/*
SPDX-FileCopyrightText: 2023-2025 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/}}

{{- if eq .Values.global.database.location "local" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.pvcName" . }}
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
{{- if .Values.persistence }}
  {{- if .Values.persistence.keepOnDelete }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end -}}
{{- end }}
spec:
{{- if or .Values.global.storageClassName .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName | default .Values.persistence.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources: {{ .Values.persistence.resources | toYaml | nindent 4 }}
{{- end }}
